## 3.1. Sorting NumPy Arrays 

### 3.1.1. Soring Numeric Arrays

In [1]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20,10)
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[17  9  5  2 12 16  8 12 12  7]

sorted array
[ 2  5  7  8  9 12 12 12 16 17]


### 3.1.2. Sorting Text Arrays

In [2]:
import numpy as np

print("unsorted array")
my_array = np.array(["Red", "Green", "Blue", "Yello"])
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
['Red' 'Green' 'Blue' 'Yello']

sorted array
['Blue' 'Green' 'Red' 'Yello']


### 3.1.3. Sorting Boolean Arrays

In [3]:
import numpy as np

print("unsorted array")
my_array = np.array([False, True, True, False, False, True, False, True])
print(my_array)

print("\nSorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[False  True  True False False  True False  True]

Sorted array
[False False False False  True  True  True  True]


### 3.1.4. Sorting 2-D Arrays

In [32]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20, size = (4,6))
print(my_array)

print("Sorted array")
sorted_array = np.sort(my_array)
print(sorted_array)

unsorted array
[[13 12 12 14 16  6]
 [ 7 18  1  2  4  2]
 [ 4 14 16 11  1 12]
 [ 8  9  9 15  2  9]]
Sorted array
[[ 6 12 12 13 14 16]
 [ 1  2  2  4  7 18]
 [ 1  4 11 12 14 16]
 [ 2  8  9  9  9 15]]


### 3.1.5. Sorting in Descending Order

In [5]:
import numpy as np

print("unsorted array")
my_array = np.random.randint(1,20,10)
print(my_array)

print("\nsorted array")
sorted_array = np.sort(my_array)
reverse_sorted = np.flipud(sorted_array)
print(reverse_sorted)

unsorted array
[15 18 16  3  2  1  4 16  2  3]

sorted array
[18 16 16 15  4  3  3  2  2  1]


## 3.2. Reshaping NumPy Arrays

### 3.2.1. Reshaping from Lower to Higher Dimensions

In [6]:
import numpy as np

print("one-dimensional array")
one_d_array = np.random.randint(1,20,10)
print(one_d_array)

print("\ntwo-dimensional array")
two_d_array = one_d_array.reshape(2,5)
print(two_d_array)

one-dimensional array
[ 4 14 12 17 18 17  2 19 18 11]

two-dimensional array
[[ 4 14 12 17 18]
 [17  2 19 18 11]]


In [7]:
import numpy as np

print("one-dimensional array")
one_d_array = np.random.randint(1,20,10)
print(one_d_array)

print("\ntwo-dimensional array")
two_d_array = np.reshape(one_d_array,(2,5))
print(two_d_array)

one-dimensional array
[ 9 17 19 16  8 15  6  6 13 17]

two-dimensional array
[[ 9 17 19 16  8]
 [15  6  6 13 17]]


In [8]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(one_d_array)

print("\nthree-dimensional array")
three_d_array = np.reshape(two_d_array,(3,4,2))
print(two_d_array)

two-dimensional array
[ 9 17 19 16  8 15  6  6 13 17]

three-dimensional array
[[17 17  3 11  9  5]
 [ 6 18  7  5 14  7]
 [14  5  4  9 11  1]
 [16  8  9  7 16 16]]


In [31]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(one_d_array)

print("\nthree-dimensional array")
three_d_array = np.reshape(two_d_array,(1,4,2))
print(two_d_array)

two-dimensional array
[14  2  2 18 19  4 16  3 14  6  5 15  3 16 10 14 14  8 12 15  1  5 16 11
  9  5  1 12 13  8  5 11 18 10 19  5 13  1  8  6 19  3 19  1  6 15 12  3]

three-dimensional array


ValueError: cannot reshape array of size 24 into shape (1,4,2)

### 3.2.2. Reshaping Higher Dimensions To Lower Dimensions

In [9]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)

print("\none-dimensional array")
one_d_array = two_d_array.reshape(24)
print(one_d_array)

two-dimensional array
[[ 6  6 15  3 11 14]
 [14  4  8 17 10  6]
 [ 5 14  3  5 15 14]
 [12  3 15 15  5 16]]

one-dimensional array
[ 6  6 15  3 11 14 14  4  8 17 10  6  5 14  3  5 15 14 12  3 15 15  5 16]


In [10]:
import numpy as np

print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)

print("\none-dimensional array")
one_d_array = two_d_array.reshape(-1)
print(one_d_array)

two-dimensional array
[[ 5 10 10 11 18 12]
 [12  3  4  7  5  2]
 [ 5 11  3  6 19  9]
 [16  2  7  6  4  4]]

one-dimensional array
[ 5 10 10 11 18 12 12  3  4  7  5  2  5 11  3  6 19  9 16  2  7  6  4  4]


In [11]:
import numpy as np

print("two-dimensional array")
three_d_array = np.random.randint(1,20, size = (4,2,6))
print(three_d_array )

print("\non-dimensional array")
one_d_array = three_d_array .reshape(-1)
print(one_d_array)

two-dimensional array
[[[14  2  2 18 19  4]
  [16  3 14  6  5 15]]

 [[ 3 16 10 14 14  8]
  [12 15  1  5 16 11]]

 [[ 9  5  1 12 13  8]
  [ 5 11 18 10 19  5]]

 [[13  1  8  6 19  3]
  [19  1  6 15 12  3]]]

on-dimensional array
[14  2  2 18 19  4 16  3 14  6  5 15  3 16 10 14 14  8 12 15  1  5 16 11
  9  5  1 12 13  8  5 11 18 10 19  5 13  1  8  6 19  3 19  1  6 15 12  3]


## 3.3. Array Indexing and Slicing

In [12]:
import numpy as np
s = np.arange(1,11)  
print(s) 


[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(s[1])  

2


In [14]:
print(s[1:9])  

[2 3 4 5 6 7 8 9]


In [15]:
print(s[:5])  
print(s[5:])  

[1 2 3 4 5]
[ 6  7  8  9 10]


In [16]:
row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
  
nums_2d = np.array([row1, row2, row3])  
print(nums_2d[:2,:])   

[[10 12 13]
 [45 32 16]]


In [17]:
row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
 
nums_2d = np.array([row1, row2, row3])  

print(nums_2d[:,:2])   

[[10 12]
 [45 32]
 [45 32]]


In [18]:
row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
 
nums_2d = np.array([row1, row2, row3])  
print(nums_2d[1:,1:]) 


[[32 16]
 [32 16]]


## 3.4. Broadcasting NumPy Arrays

In [19]:
import numpy as np

array1 = np.array ([14,25,31])
array2 = np.array([10])
result = array1 + array2 
print(result)

[24 35 41]


In [20]:

array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([10])

print("after bradcasting")
result = array1 + array2 
print(result)

[[ 2 11 16 19]
 [14 15 13 19]
 [ 9  6 18  4]]
after bradcasting
[[12 21 26 29]
 [24 25 23 29]
 [19 16 28 14]]


In [21]:

array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([5,10,20,25])

print("after bradcasting")
result = array1 + array2 
print(result)

[[ 4  6  1  2]
 [19  2 16  7]
 [19  7 19  6]]
after bradcasting
[[ 9 16 21 27]
 [24 12 36 32]
 [24 17 39 31]]


In [22]:
array1 = np.random.randint(1,20, size = (3,4))
print(array1)

array2 = np.array([[5],[10],[20]])

print("after bradcasting")
result = array1 + array2 
print(result)

[[10 17  7  3]
 [19  9 14 17]
 [11 15 11 10]]
after bradcasting
[[15 22 12  8]
 [29 19 24 27]
 [31 35 31 30]]


## 3.5. Copying NumPy Arrays

In [23]:
import numpy as np
array1 = np.array([10,12,14,16,18,20])

array2 = array1.copy()
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [24]:
array1 = np.array([10,12,14,16,18,20])

array2 = np.copy(array1)
array2[1] = 20

print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]


In [25]:
array1 = np.array([10,12,14,16,18,20])

array2 = array1.view()
array2[1] = 20

print(array1)
print(array2)

[10 20 14 16 18 20]
[10 20 14 16 18 20]


## 3.6. NumPy I/O Operations

### 3.6.1. Saving a NumPy Array

In [26]:
import numpy as np
array1 = np.array([10,12,14,16,18,20])

np.save("D:\Datasets\my_array", array1)

In [27]:
import numpy as np
array1 = np.array([10,12,14,16,18,20])

np.savetxt("D:\Datasets\my_array.txt", array1)

### 3.6.2. Loading a NumPy Array

In [28]:
import numpy as np
loaded_array = np.load("D:\Datasets\my_array.npy")
print(loaded_array)

[10 12 14 16 18 20]


In [29]:
import numpy as np
loaded_array = np.loadtxt("D:\Datasets\my_array.txt")
print(loaded_array)

[10. 12. 14. 16. 18. 20.]


## Exercise 3.1


**Question 1:**

Which function is used to convert a multi-dimensional NumPy array into a flat array of 1-dimension?

A- np.reshape(0)

B- np.reshape(-1)

C- np.reshape(1)

D- None of the Above

Answer: B


**Question 2:**

Which function is used to save a NumPy array in text format?

A- np.savetext()

B- np.saveText()

C- np.saveTxt()

D- np.savetxt()

Answer: D


**Question 3:**

To sort a NumPy array in descending order, you can use the following function:

A- np.flipud(np.sort(my_array))

B- np.sort(np.flip(my_array))

C- np.sort()

D- np.flip()

Answer: A

## Exercise 3.2

Create a random NumPy array of 4 rows and 5 columns. Using array indexing and slicing, display the items from row 3 to end and column 2 to end.

**Solution:**

In [30]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)
print("Result")
print(uniform_random[2:,1:])

[[0.85857741 0.88078705 0.89522148 0.34468533 0.96228498]
 [0.18203911 0.596476   0.11543116 0.65926056 0.32393406]
 [0.8753794  0.11287922 0.40874252 0.26130304 0.21163474]
 [0.95970259 0.65384791 0.31048958 0.10952554 0.86016743]]
Result
[[0.11287922 0.40874252 0.26130304 0.21163474]
 [0.65384791 0.31048958 0.10952554 0.86016743]]
