## 2.2. NumPy Data Types

In [1]:
import numpy as np

my_array = np.array([10,12,14,16,20,25])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

[10 12 14 16 20 25]
int32
4


In [2]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['Red' 'Green' 'Orange']
<U6
24


In [3]:
import numpy as np

my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"])

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
<U10
40


In [4]:
my_array3 = my_array.astype("M")

print(my_array3.dtype)
print(my_array3.dtype.itemsize)

datetime64[D]
8


In [5]:
import numpy as np

my_array = np.array(["1990-10-04", "1989-05-06", "1990-11-04"], dtype = "M")

print(my_array)
print(my_array.dtype)
print(my_array.dtype.itemsize)

['1990-10-04' '1989-05-06' '1990-11-04']
datetime64[D]
8


## 2.3. Creating NumPy Arrays

### 2.3.1 Using Array Method

In [6]:
import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)    



numpy.ndarray

In [7]:
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1, row2, row3])
nums_2d.shape 
             

(3, 3)

### 2.3.2. Using Arange Method

In [8]:
nums_arr = np.arange(5,11)
print(nums_arr)


[ 5  6  7  8  9 10]


In [9]:
nums_arr = np.arange(5,12,2)
print(nums_arr)


[ 5  7  9 11]


### 2.3.3. Using Ones Method

In [10]:
ones_array = np.ones(6)
print(ones_array)


[1. 1. 1. 1. 1. 1.]


In [11]:
ones_array = np.ones((6,4))
print(ones_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 2.3.4. Using Zeros Method

In [12]:
zeros_array = np.zeros(6)
print(zeros_array)


[0. 0. 0. 0. 0. 0.]


In [13]:
zeros_array = np.zeros((6,4))
print(zeros_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 2.3.5. Using Eyes Method

In [14]:
eyes_array = np.eye(5)
print(eyes_array)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 2.3.6. Using Random Method

In [15]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)

[[0.11119162 0.81438748 0.96099658 0.74265594 0.48338977]
 [0.15983244 0.12608595 0.49575616 0.3070778  0.5436102 ]
 [0.25755473 0.44593054 0.53837663 0.80588277 0.29575403]
 [0.17133592 0.79378823 0.65926258 0.96585302 0.23110197]]


In [16]:
normal_random = np.random.randn(4, 5)
print(uniform_random)

[[0.11119162 0.81438748 0.96099658 0.74265594 0.48338977]
 [0.15983244 0.12608595 0.49575616 0.3070778  0.5436102 ]
 [0.25755473 0.44593054 0.53837663 0.80588277 0.29575403]
 [0.17133592 0.79378823 0.65926258 0.96585302 0.23110197]]


In [17]:
integer_random = np.random.randint(10, 50, 5)
print(integer_random)

[25 28 18 16 14]


## 2.4. Printing NumPy Arrays

In [18]:
import numpy as np

my_array = np.array([10,12,14,16,20,25])
print(my_array)

[10 12 14 16 20 25]


In [19]:
print(my_array.ndim)
print(my_array.shape)

1
(6,)


In [20]:
for i in my_array:
    print(i)

10
12
14
16
20
25


In [21]:
integer_random = np.random.randint(1,11, size=(4, 5))
print(integer_random)

[[ 2  8  3  2  6]
 [ 2  9  7  2  6]
 [10  3 10 10 10]
 [ 4  2  8  7 10]]


In [22]:
print(integer_random.ndim)
print(integer_random.shape)

2
(4, 5)


In [23]:
for i in integer_random:
    print(i)

[2 8 3 2 6]
[2 9 7 2 6]
[10  3 10 10 10]
[ 4  2  8  7 10]


In [24]:
for rows in integer_random:
    for column in rows:
        print(column)

2
8
3
2
6
2
9
7
2
6
10
3
10
10
10
4
2
8
7
10


## 2.5. Adding Items in an Array

In [25]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

extended = np.append(my_array, "Yellow")
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow']


In [26]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

extended = np.append(my_array, ["Yellow", "Pink"])
print(extended)

['Red' 'Green' 'Orange']
['Red' 'Green' 'Orange' 'Yellow' 'Pink']


In [27]:
zeros_array = np.zeros((3,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
zeros_array = np.zeros((3,3))
print(zeros_array)
print("Extended Array")
extended = np.append(zeros_array, [[1, 2, 3]], axis = 0)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 2. 3.]]


In [29]:
zeros_array = np.zeros((3,3))
print(zeros_array)
print("Extended Array")
extended = np.append(zeros_array, [[1],[2],[3]], axis = 1)
print(extended)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Extended Array
[[0. 0. 0. 1.]
 [0. 0. 0. 2.]
 [0. 0. 0. 3.]]


## 2.6. Removing Items From an Array

In [30]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

print("After deletion")
updated_array = np.delete(my_array, 1)
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red' 'Orange']


In [31]:
import numpy as np

my_array = np.array(["Red", "Green", "Orange"])
print(my_array)

print("After deletion")
updated_array = np.delete(my_array, [1,2])
print(updated_array)

['Red' 'Green' 'Orange']
After deletion
['Red']


In [32]:
integer_random = np.random.randint(1,11, size=(4, 5))
print(integer_random)

print("After deletion")
updated_array = np.delete(integer_random, 1, axis = 0)
print(updated_array)

[[ 4  6  5  2  5]
 [ 3  4  8  4  5]
 [ 1  4  6  1 10]
 [ 2  8  8  1  8]]
After deletion
[[ 4  6  5  2  5]
 [ 1  4  6  1 10]
 [ 2  8  8  1  8]]


In [33]:
integer_random = np.random.randint(1,11, size=(4, 5))
print(integer_random)

print("After deletion")
updated_array = np.delete(integer_random, 1, axis = 1)
print(updated_array)

[[ 6  8  9  2  9]
 [ 5  9  4 10  1]
 [10  6  1  9  6]
 [ 2  4  6  8  5]]
After deletion
[[ 6  9  2  9]
 [ 5  4 10  1]
 [10  1  9  6]
 [ 2  6  8  5]]


## Excersise 2.1


**Question 1:**

To generate an identity matrix of 4 rows and 4 columns, which of the following functions can be used?

A- np.identity(4,4)

B- np.id(4,4)

C- np.eye(4,4) 

D- All of the above

Answer: C


**Question 2:**

To delete a column from 2-Dimensional NumPy array, the value of the axis attribute of the delete method should be set to:?

A- 0

B- 1

C- column_number

D- All of the above

Answer: B


**Question 3:**

How to create the array of numbers 4,7,10,13,16 with NumPy: 

A- np.arange(3, 16, 3)

B- np.arange(4, 16, 3)

C- np.arange(4, 15,3) 

D- None of the above

Answer: D

## Excersise 2.2

Create a random NumPy array of 5 rows and 4 columns.

**Solution:**

In [34]:
import numpy as np
uniform_random = np.random.rand(4, 5)
print(uniform_random)

[[0.82072471 0.3817491  0.93811218 0.82668843 0.19386928]
 [0.8845797  0.06173116 0.16080164 0.04427864 0.18056586]
 [0.3110957  0.69422148 0.57489394 0.8384647  0.64360883]
 [0.70645336 0.11615612 0.50188594 0.36384901 0.17326382]]
