## 5.1. Arithmetic Operations with NumPy

### 5.1.1. Finding Square Roots

In [1]:
import numpy as np

nums = [10,20,30,40,50]  
np_sqr = np.sqrt(nums)  
print(np_sqr) 

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


### 5.1.2.Finding Logs

In [2]:
import numpy as np

nums = [10,20,30,40,50]  
np_log = np.log(nums)  
print(np_log )


[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


### 5.1.3. Finding Exponents

In [3]:
import numpy as np

nums = [10,20,30,40,50]  
np_exp = np.exp(nums)  
print(np_exp)  

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


### 5.1.4. Finding Since and Cosine

In [4]:
import numpy as np

nums = [10,20,30,40,50]  
np_sine = np.sin(nums)  
print(np_sine)  
 
nums = [10,20,30,40,50]  
np_cos = np.cos(nums)  
print(np_cos)  

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


## 5.2. Linear Algebra Operations with NumPy

### 5.2.1. Finding Matrix Dot Product

In [5]:
import numpy as np

A = np.random.randn(4,5)  
B = np.random.randn(5,4)  
 
Z =  np.dot(A,B)   
print(Z)  


[[-2.69338193 -1.61225935  0.61750607 -0.88609413]
 [ 1.94422502 -0.09992377  0.62015396  0.43694466]
 [-2.2216779   0.02529759  1.1457269  -0.2811504 ]
 [-0.019766   -4.56155475  0.52781149  1.94851995]]


### 5.2.2.	Element-wise Matrix Multiplication

In [6]:
import numpy as np

row1 = [10,12,13]  
row2 = [45,32,16]  
row3 = [45,32,16]  
 
nums_2d = np.array([row1, row2, row3])  
multiply = np.multiply(nums_2d, nums_2d)  
print(multiply)


[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


### 5.2.3. Finding Matrix Inverse

In [7]:
import numpy as np

row1 = [1,2,3]  
row2 = [5,2,8]  
row3 = [9,1,10]  
 
nums_2d = np.array([row1, row2, row3])  
 
inverse = np.linalg.inv(nums_2d)  
print(inverse)  

[[ 0.70588235 -1.          0.58823529]
 [ 1.29411765 -1.          0.41176471]
 [-0.76470588  1.         -0.47058824]]


### 5.2.4. Finding Matrix Determinant

In [8]:
import numpy as np

row1 = [1,2,3]  
row2 = [5,2,8]  
row3 = [9,1,10]    
    
nums_2d = np.array([row1, row2, row3])    
    
determinant = np.linalg.det(nums_2d)    
print(determinant)    

17.0


### 5.2.5. Finding Matrix Trace

In [9]:
import numpy as np

row1 = [1,2,3]  
row2 = [4,5,6]  
row3 = [7,8,9]  
  
nums_2d = np.array([row1, row2, row3])  
  
trace = np.trace(nums_2d)  
print(trace)  

15


### 5.2.6. Solving a System of Linear Equations with Python

In [10]:
#two equations

# 6x + 3y = 42
# 2x + 4y = 32


In [11]:
import numpy as np

A = np.array([[6, 3],
              [2, 4]])

B = np.array([42, 32])
             

In [12]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.22222222 -0.16666667]
 [-0.11111111  0.33333333]]


In [13]:
X = np.dot(A_inv, B)
print(X)

[4. 6.]


## Exercise 5.1


**Question 1:**

How to find the dot product between two numpy arrays A and B:?

A- numpy.dot(A,B) 

B- A.dot(B) 

C- Both A and B

D- None of the above

Answer: C


**Question 2:**

How to find the determinant of a Matrix A?

A- numpy.linalg.det(A)

B- numpy.det(A)

C- linalg.det(A)

D- All of the above


Answer: A


**Question 3:**

How to find the sine of a items in a NumPy array:

A- numpy.sine() 

B- numpy.sin()  

C- numpy.linalg.sin() 

D- None of the above

Answer: B

## Exercise 5.2

Solve the following system of of three linear equations and find the values of variables x, y, and z:

`3x + 4y + 2z = 17`

`5x + 2y + 3z = 23`

`4x + 3y + 2z = 19`



**Solution:**

In [14]:
import numpy as np

A = np.array([[3, 4, 2],
              [5, 2, 3],
              [4, 3, 2]])

B = np.array([17, 23, 19])


X = np.linalg.inv(A).dot(B)
print(X)

[3. 1. 2.]
